# Generated by Django 3.1.3 on 2021-06-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20210611_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
